### ISSUE TITLE
Not working in Chrome Version 88.0.4324.182 (Offizieller Build) (64-Bit) (Linux)

### ISSUE THREAD

**Issue by JanAckermann1337** [loilo/auto-group-tabs#1]
I created the URL pattern but it is not working. 
Pattern: app.datadoghq.eu
URL i visit: https://app.datadoghq.eu/*************/*************  

Am i doing something wrong ?

**Comment by loilo** [comment]
Huh — I did not realize the extension was already online. Have gotten no report from Google that the review process was done. 😅 
Yes, I had a bug in the path wildcard in the version I sent for review but couldn't update it while being reviewed. Have the bug already fixed in this repo and will try to push an update for the extension ASAP.

Thanks for making me aware of this. 😁

**Comment by loilo** [comment]
Okay, I've submitted the fixed version for review. (Oof, publishing an extension is quite a slow process, but it's for the better of all of us I guess.)

I'll check for the review status every now and then and close this issue as soon as the new version is published. Thanks again for reporting!

**Comment by JanAckermann1337** [comment]
Cool thank you. Yeah i know the struggle with extensions i also have one.

**Comment by loilo** [comment]
Yep, it's my first one. Well, it's a learning experience. 😁

**Comment by JanAckermann1337** [comment]
I am now on version 0.0.2 is this the one with the fix? If yes it is still not working.
I could get the code and build it myself and then maybe i can give you a better error message.

**Comment by loilo** [comment]
It should work now. However there are two caveats (and I should probably find a separate fix for this): When the extension is freshly installed, the extension's service worker is not running in existing tabs. It should work in a new tab/window though.

That said: Are you still running Chrome 88? The `tabGroups` API is only available in Chrome 89 and upwards.

**Comment by loilo** [comment]
I'll close this issue as the original bug has been resolved in 0.0.2. If it's still not working for you, feel free to ping me here @JanAckermann1337.

Side note: From v0.0.3 (which is currently under review) onwards, the extension's behavior now *should* automatically update itself in existing tabs as well (see 2e2a64af4b8f4953301e9549e211b181461cdd2f). However, I cannot guarantee this to work yet since it's naturally hard to test in development. 😉
